### ISSUE TITLE
aggregations not working on _id field in mongo 

### ISSUE THREAD

**Issue by HeyItsJs** [spaceuptech/space-cloud#1382]
### Describe the bug

The new aggregate syntax doesn't work if we aggregate the `_id` field. For example:

```
query {
  users @mongo {
    _id @aggregate(op: count)
  }
}
```

Also sometimes randomly this query crashes the gateway with a panic error:
```2020-10-26T12:46:58.565+0530	INFO	server/middleware.go:28	Request	{"requestId": "1jPD1Wzi5bIsvHF2bMmX5OOtJ0A", "fields": {"body":"{\"operationName\":null,\"variables\":{\"join\":[{\"type\":\"LEFT\",\"table\":\"posts\",\"on\":{\"users.id\":\"posts.user_id\"}}]},\"query\":\"{\\n  users @mongo {\\n    _id @aggregate(op: count)\\n  }\\n}\\n\"}","method":"POST","queryVars":{},"url":"/v1/api/test/graphql"}}
panic: interface conversion: interface {} is int32, not map[string]interface {}

goroutine 75 [running]:
github.com/spaceuptech/space-cloud/gateway/modules/crud/mgo.getNestedObject(0xc000c43950)
	/home/heyitsjs/space-up/go/space-cloud/gateway/modules/crud/mgo/read.go:337 +0x673
github.com/spaceuptech/space-cloud/gateway/modules/crud/mgo.(*Mongo).Read(0xc0006884b0, 0x25bc1e0, 0xc000b94ae0, 0xc000b00478, 0x5, 0xc000ae2310, 0x0, 0x0, 0x0, 0x0, ...)
	/home/heyitsjs/space-up/go/space-cloud/gateway/modules/crud/mgo/read.go:149 +0x13d0
github.com/spaceuptech/space-cloud/gateway/modules/crud.(*Module).Read(0xc0004263c0, 0x25bc1e0, 0xc000b94ae0, 0xc000b00480, 0x5, 0xc000b00478, 0x5, 0xc000ae2310, 0x0, 0x0, ...)
	/home/heyitsjs/space-up/go/space-cloud/gateway/modules/crud/operations.go:84 +0x65e
github.com/spaceuptech/space-cloud/gateway/utils/graphql.(*Module).execReadRequest.func1(0xc000ae2310, 0xc00028be00, 0xc00004cf50, 0x25bc1e0, 0xc000b94ae0, 0xc000b00480, 0x5, 0xc000b00478, 0x5, 0x0, ...)
	/home/heyitsjs/space-up/go/space-cloud/gateway/utils/graphql/read.go:114 +0x115
created by github.com/spaceuptech/space-cloud/gateway/utils/graphql.(*Module).execReadRequest
	/home/heyitsjs/space-up/go/space-cloud/gateway/utils/graphql/read.go:110 +0x6a
```

 
### Your environment
- Space Cloud version: v0.19.6
- Database: Mongo DB

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
You can use `count @aggregate(op: count, field: all)`
