### ISSUE TITLE
Panic on not specifying selection set on the "payload" object in the GraphQL subscriptions

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-cloud#908]
### Describe the bug
If I make the following GraphQL query to Space Cloud:
```graphql
subscription {
    todos (where: {userId: {_eq: "${userId}"}}) @mydb {
      type
      payload
    }
  }
```
Space Cloud panics with the following error:
```bash
2020-04-04 13:59:57.339529 I | http: panic serving [::1]:41560: runtime error: invalid memory address or nil pointer dereference
goroutine 55 [running]:
net/http.(*conn).serve.func1(0xc00096eb40)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1dfb420, 0x366df20)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/spaceuptech/space-cloud/gateway/utils/handlers.filterGraphqlSubscriptionResults(0xc000300480, 0xc000756080, 0xa)
	/home/heyitsjs/space-up/go/space-cloud/gateway/utils/handlers/websocket.go:311 +0x22f
github.com/spaceuptech/space-cloud/gateway/utils/handlers.HandleGraphqlSocket.func1(0x2593080, 0xc0009940e0, 0xc00010c500)
	/home/heyitsjs/space-up/go/space-cloud/gateway/utils/handlers/websocket.go:277 +0x11a4
net/http.HandlerFunc.ServeHTTP(0xc0008330c0, 0x2593080, 0xc0009940e0, 0xc00010c500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00071c240, 0x2593080, 0xc0009940e0, 0xc00010c000)
	/home/heyitsjs/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/spaceuptech/space-cloud/gateway/utils/server.(*Server).restrictDomainMiddleware.func1(0x2593080, 0xc0009940e0, 0xc00010c000)
	/home/heyitsjs/space-up/go/space-cloud/gateway/utils/server/http.go:30 +0x18e
net/http.HandlerFunc.ServeHTTP(0xc000815a00, 0x2593080, 0xc0009940e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x2593080, 0xc0009940e0, 0xc00010c000)
	/home/heyitsjs/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc00088f200, 0x2593080, 0xc0009940e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/spaceuptech/space-cloud/gateway/utils/handlers.HandleMetricMiddleWare.func1(0x2593080, 0xc0009940e0, 0xc00010c000)
	/home/heyitsjs/space-up/go/space-cloud/gateway/utils/handlers/metric_middleware.go:24 +0x2f6
net/http.HandlerFunc.ServeHTTP(0xc00088f220, 0x2593080, 0xc0009940e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/mholt/certmagic.(*Config).HTTPChallengeHandler.func1(0x2593080, 0xc0009940e0, 0xc00010c000)
	/home/heyitsjs/go/pkg/mod/github.com/mholt/certmagic@v0.9.1/httphandler.go:37 +0xa1
net/http.HandlerFunc.ServeHTTP(0xc00088f240, 0x2593080, 0xc0009940e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0008c2000, 0x2593080, 0xc0009940e0, 0xc00010c000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00096eb40, 0x259c2c0, 0xc000814000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
2020-04-04 13:59:57.408071 I | http: panic serving [::1]:41562: runtime error: invalid memory address or nil pointer dereference
```

The error gets resolved if I specify the selection set or fields within the `payload` like this:
```graphql
subscription {
    todos (where: {userId: {_eq: "${userId}"}}) @mydb {
      type
      payload {
        _id
        value
        isCompleted
      }
    }
  }
```
### Expected behaviour
The subscription query should work even without specifying the inner fields of payload.

### Actual behaviour 
Space Cloud panics with the error.

### Your environment
- Space Cloud version: v0.17.0
- OS:
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Fixed in `v0.17.0`
